name = "captain-fripp-support"
compatibility_date = "2024-01-01"

[env.production]
name = "captain-fripp-support"

[env.preview]
name = "captain-fripp-support-preview"

# Cloudflare Pages configuration
pages_build_output_dir = "."
